### ISSUE TITLE
Postgresql Support ?

### ISSUE THREAD

**Issue by glz-io** [fjies/dashboard#111] opened 2015-03-09 09:59 UTC
Hi,

It could be great to have postgresql support for OC Dashboard.

Regards

**Comment by fjies** [comment] 2015-03-09 10:57
for wich version?
the new 1.6.x version?

Do I have to implement some special code to support postgreesql?
I thought the new version supports all dbms.

**Comment by glz-io** [comment] 2015-03-09 11:05
Sorry for the missing informations.

I was talking about the last version of owncloud and the last version of OC Dashboard coming from app.owncloud.com

After installation, I have a message: "Can not activate, this app only support mysql or sqlite".

**Comment by fjies** [comment] 2015-03-09 11:54
well yes, thats correct.
Somebody told me, that he tried to use postgre and thats not working.
Thats why I named the dependecies.
I can not check that myself.

Is there anything again using the new verion?
Are there any problems with it?
I'm really interested in...

**Comment by glz-io** [comment] 2015-03-09 11:59
I've just downloaded "master" version from github and it is not working

Here is the message:

###
Dashboard
1.6.1
par Florian Steffens (AGPL-Sous licence)
Recommended

The dashboard app presents you quick and smart information.

Cette application ne peut être installée à cause de ces dépendances non satisfaites :

    Following databases are supported: sqlite, mysql
###

**Comment by fjies** [comment] 2015-03-09 15:36
There were keys in the config missing.
Thanks for the info. I changed it in the master branch.
Can you try that out for me?

**Comment by glz-io** [comment] 2015-03-09 16:00
This is ok, I can enable the App now.

Thx a lot

**Comment by glz-io** [comment] 2015-03-09 16:09
But after, we I click on dashboard in the menu, I have an error:

{"reqId":"677aef4fcf8ea2ebecaa11f36cb6f205","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT * FROM \\\"oc_dashboard_config\\\" WHERE \\\"user\\\" = ? AND \\\"key\\\" = ? AND \\\"value\\\" = ? ORDER BY \\\"id\\\" DESC' with params [\\\"admin\\\", \\\"enabled\\\", \\\"1\\\"]:\\n\\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \\\"oc_dashboard_config\\\" does not exist\\nLINE 1: SELECT * FROM \\\"oc_dashboard_config\\\" WHERE \\\"user\\\" = $1 AND \\\"k...\\n                      ^\",\"Code\":0,\"Trace\":\"#0 \\\/xxx\\\/xxx\\\/xxx\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/xxx\\\/xxx\\\/xxx\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM \\\"...', Array)\\n#2 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/private\\\/db\\\/statementwrapper.php(63): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/xxx\\\/xxx\\\/xxx\\\/apps\\\/dashboard\\\/db\\\/widgetconfigdao.php(95): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/xxx\\\/xxx\\\/xxx\\\/apps\\\/dashboard\\\/controller\\\/pagecontroller.php(76): OCA\\\\Dashboard\\\\Db\\\\WidgetConfigDAO->findEnabledWidgets('admin')\\n#5 \\\/xxx\\\/xxx\\\/xxx\\\/apps\\\/dashboard\\\/controller\\\/pagecontroller.php(55): OCA\\\\Dashboard\\\\Controller\\\\PageController->getEnabledWidgets()\\n#6 [internal function]: OCA\\\\Dashboard\\\\Controller\\\\PageController->index()\\n#7 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#8 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Dashboard\\\\Controller\\\\PageController), 'index')\\n#9 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Dashboard\\\\Controller\\\\PageController), 'index')\\n#10 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/xxx\\\/xxx\\\/xxx\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/dashboard...')\\n#14 \\\/xxx\\\/xxx\\\/xxx\\\/index.php(36): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/xxx\\\/xxx\\\/xxx\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":75}","level":4,"time":"2015-03-09T16:05:00+00:00"}

**Comment by fjies** [comment] 2015-03-09 17:01
Please reinstall the app. There is a table missing. Maybe that is caused by your different installation tries.

**Comment by glz-io** [comment] 2015-03-09 17:12
I've one some cleaning in pgsql database: remove tables and lines from appconfig table

Activate is working, but when I add a widget, I have this error:

{"reqId":"cc50fa7fe1319e4f80b0044b33bb97a2","remoteAddr":"92.103.106.88","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT wNo FROM \\\"oc_dashboard_config\\\" WHERE \\\"wId\\\" = ? AND \\\"user\\\" = ? ORDER BY wNo DESC LIMIT 1' with params [\\\"dummy\\\", \\\"admin\\\"]:\\n\\nSQLSTATE[42703]: Undefined column: 7 ERROR:  column \\\"wno\\\" does not exist\\nLINE 1: SELECT wNo FROM \\\"oc_dashboard_config\\\" WHERE \\\"wId\\\" = $1 AND \\\"...\\n               ^\",\"Code\":0,\"Trace\":\"#0 \\\/xx\\\/xx\\\/xx\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/xx\\\/xx\\\/xx\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT wNo FROM...', Array)\\n#2 \\\/xx\\\/xx\\\/xx\\\/lib\\\/private\\\/db\\\/statementwrapper.php(63): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/xx\\\/xx\\\/xx\\\/apps\\\/dashboard\\\/db\\\/widgetconfigdao.php(78): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/xx\\\/xx\\\/xx\\\/apps\\\/dashboard\\\/controller\\\/widgetcontroller.php(169): OCA\\\\Dashboard\\\\Db\\\\WidgetConfigDAO->getHighestNo('dummy', 'admin')\\n#5 [internal function]: OCA\\\\Dashboard\\\\Controller\\\\WidgetController->addNew('dummy')\\n#6 \\\/xx\\\/xx\\\/xx\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#7 \\\/xx\\\/xx\\\/xx\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Dashboard\\\\Controller\\\\WidgetController), 'addNew')\\n#8 \\\/xx\\\/xx\\\/xx\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Dashboard\\\\Controller\\\\WidgetController), 'addNew')\\n#9 \\\/xx\\\/xx\\\/xx\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('WidgetControlle...', 'addNew', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/xx\\\/xx\\\/xx\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/xx\\\/xx\\\/xx\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/dashboard...')\\n#13 \\\/xx\\\/xx\\\/xx\\\/index.php(36): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/xx\\\/xx\\\/xx\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":72}","level":4,"time":"2015-03-09T17:09:39+00:00"}

**Comment by glz-io** [comment] 2015-03-09 17:15
Strange thing:
 public | oc_dashboard_config          | table | owncloud
 public | oc_dashboard_usedHashs       | table | owncloud
-> tables are present

owncloud=# select * from oc_dashboard_config ;
 id | user | wId | wNo | key | value 
----+------+-----+-----+-----+-------
(0 rows)

owncloud=# select * from oc_dashboard_usedHashs ;
ERROR:  relation "oc_dashboard_usedhashs" does not exist
LINE 1: select * from oc_dashboard_usedHashs ;
                      ^

**Comment by mckaygerhard** [comment] 2015-03-09 22:32
for postgres case sensityve are required. many of the errors are due this .. seems development are under guindws..

**Comment by fjies** [comment] 2015-03-10 07:27
@mckaygerhard thats what I tried to do correct.
The definition for example is **wNo** and the error query says "SELECT **wNo** FROM" but the error message is "Undefined column: 7 ERROR: column \\"**wno**\\"". Can you give me a hint what I have to do to fix that?

**Comment by mckaygerhard** [comment] 2015-03-10 13:30
thyere two errors , not one error... 

all are casesensitive related.. i clone the repo and tried the query in postgres but i changed all references to lowercase.. query does not fail this time..

u are making the query in mocosoft wuindows winbuntu or someting and thats the reason of the errors

**Comment by fjies** [comment] 2015-03-10 14:09
@mckaygerhard thanks a lot, I will try that out at home next time

**Comment by mckaygerhard** [comment] 2015-03-11 16:48
i recommend to use REAL OS such linux  debian and not a windo like to avoid this misctakes..

**Comment by fjies** [comment] 2015-03-11 20:12
okay, i committed some changes, that worked for me with a postgresql.
Update script is not ready.
Maybe you can try that?

@mckaygerhard I'm working with a linux based machine.

**Comment by mckaygerhard** [comment] 2015-03-11 20:23
of course i can try, i wait for this type of app for oc for long time (i try to ported to postgres but see too many querys and must study the code, so ...)

i think update script are not necesary.. i think still only 2 people used postres as db backend, and only me used in a large production system. so script now will be unnecesary...

**Comment by mckaygerhard** [comment] 2015-03-11 20:46
error:

```
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/simplenet/apps/dashboard/appinfo/app.php on line 19
```

**Comment by fjies** [comment] 2015-03-11 20:50
strange, I didn't change something in there.

**Comment by mckaygerhard** [comment] 2015-03-11 21:12
the error are due the issue that wwe are already discuss now.. around php 5.3 vs 5.4  , about this issue u can close , postgresql support are done (for now)

**Closed** 2015-03-11 21:13 UTC
Labels: bug

**Comment by glz-io** [comment] 2015-03-12 10:04
Thx, this is working well.

I've deleted all postgres tables, etc. Re-install master version.
